use super::vec::*;
pub type Vec3 = Vector<3>;
pub type Color = Vector<3>;
pub type Normal = Vector<3>;
pub type Position = Vector<3>;
pub type Direction = Vector<3>;
pub type Barycentrics = Vector<2>;
//pub type FragCoord = IVec2;
pub type TextureCoordinate = Vector<2>;
//pub type Transform = Mat3x4;
